# TODO - Import the logo to the game
# TODO - Make the computer select a number between 1 and 100
# TODO - Change the attempts by 10 for easy and by 5 for hard
# TODO - Identify if my guess was higher or lower then the selected number
# TODO - Create a loop to make the game continuing until I guess corectly
# TODO - Now, reduce my attempts by every mistake I made and stops when it's 0...

import random

import art

def random_number():
    """
    Makes the computer select randomly a number between 1 and 100
    :return: random number and insert it inside the global variable number
    """

    global number

    print("Welcome to the Number Guessing Game! \n"
          "I'm thinking of a number between 1 and 100.")

    number = random.randint(1, 100)
    return number



def select_difficulty():

    """
    Changes the number of attempts based on the difficulty selected by the user
    :return: 10 attempts for easy mode and 5 for hard mode
    """

    global attempts
    difficulty = input("Choose a difficulty. Type 'easy' or 'hard': ")

    if difficulty == 'easy':
        attempts += 10
    else:
        attempts += 5

    return attempts


def compare():

    """
    Checks the user guess and compare to the random number generated by the computer
    Alerts the player if the guess is higher or lower than the number
    Stops the game in case the player guessed correctly
    Also checks if the user used all it's attempts and stops the game
    :return:
    """

    global guess
    global number
    global attempts
    global game_is_over

    attempts -= 1

    if attempts == 0:
        print(f"\nYou've run out of guesses. The correct answer is {number}"
              f"\nRefresh the page to run again")
        game_is_over = True

    else:
        if guess == number:
            print(f"\nYou've got it, the answer was {number}")
            game_is_over = True

        elif guess < number:
            print("\nToo low \nGuess again")

        else:
            print("\nToo high \nGuess again")



# Global variables
attempts = 0 #changes according the difficulty of the game
number = 0 #computer selects it randomly



# Start of the game
print(art.logo)

random_number()
select_difficulty()
game_is_over = False

while game_is_over is False:

    print(f"\nYou have {attempts} attempts remaining to guess the number")
    guess = int(input("Make a guess: "))

    compare()






